upstream order_backend {
    keepalive 64;
    server order-service-a:8001 weight=10;
    server order-service-b:8001 weight=0;
}

upstream inventory_backend {
    keepalive 64;
    server inventory-service-a:8002 weight=10;
    server inventory-service-b:8002 weight=0;
}

upstream payment_backend {
    keepalive 64;
    server payment-service-a:8003 weight=10;
    server payment-service-b:8003 weight=0;
}

upstream user_backend {
    keepalive 64;
    server user-service-a:8004 weight=10;
    server user-service-b:8004 weight=0;
}
